name: Streamlit CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          buildkitd-config-inline: |
            [registry."129.168.2.30:6000"]
              http = true
              insecure = true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Format with black
        run: |
          pip install black
          black main.py app.py

      - name: Build Docker image
        run: |
          docker build -t my-streamlit-app:latest .

      - name: Tag Docker image
        run: |
          docker tag my-streamlit-app:latest dilawaizkhan/my-streamlit-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push dilawaizkhan/my-streamlit-app:latest

      - name: SSH to remote main server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "Deploying to deployment server..."
            cd ~/dilawaiz
            docker-compose down
            docker-compose pull
            docker-compose up -d
          timeout: 60s
