name: Streamlit CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          buildkitd-config-inline: |
            [registry."203.128.11.19:6000"]
              http = true
              insecure = true

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            YOUR_REGISTRY_IP:6000/my-streamlit-app:${{ github.sha }}
            YOUR_REGISTRY_IP:6000/my-streamlit-app:latest

      - name: Check SSH connection
        run: nc -zv 203.128.11.19 22

      - name: SSH to remote server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to deployment server..."
            docker-compose down
            docker-compose pull
            docker-compose up -d
