name: Streamlit CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Format with black
        run: |
          pip install black
          black main.py app.py

      - name: Build Docker image
        run: |
          docker build -t my-streamlit-app:latest .

      - name: Tag Docker image
        run: |
          IMAGE_TAG=latest-$(date +%Y%m%d%H%M%S)
          docker tag my-streamlit-app:latest dilawaizkhan/my-streamlit-app:${IMAGE_TAG}
        env:
          IMAGE_TAG: latest-$(date +%Y%m%d%H%M%S)

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push dilawaizkhan/my-streamlit-app:${IMAGE_TAG}
        env:
          IMAGE_TAG: latest-$(date +%Y%m%d%H%M%S)

      - name: Run Streamlit App
        run: |
          streamlit run app.py &
        env:
          OPENAI_API_KEY: ${{ secrets.GROQ_API_KEY }}

      # Optional: Add testing steps here if you have tests

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying the app..." # Replace with actual deployment commands if necessary
